### ISSUE TITLE
XDJ-RX2 - Could not autoconfigure network: no CDJs on network

### ISSUE THREAD

**Issue by NemisisDragon** [EvanPurkhiser/prolink-tools#13]
Hello,

I have following setup:
1. XDJ-RX2 connected with USB to Win10 PC with Rekordbox 5.x
2. RasperyPI Linux Server

The XDJ-RX2 is connected directly with USB to the PC. On the PC there's a Pioneer DJ Network Adapter, I guess especially for this usb-bridge. It's not possible to ping/access the IP-address from other PCs in the same network.

Issue:
When I start prolink-server on the PC with the rekordbox it seems to detect the XJD-RX2 system. But I get a "Could not autoconfigure network: no CDJs on network" error message. After reading, I figured out, that it's not possible to launch the server on the same host Rekordbox is running.

So I tried to run the Linux version on my Linux Server. It doesn't detect the XDJ-RX2 system, plus I also get "Could not autoconfigure network: no CDJs on network".

Am I doing something wrong or is the usb-bridge solution simply not possible/supported atm?
Thank you very much in advance for your help!

**Comment by noriega3** [comment]
https://github.com/EvanPurkhiser/prolink-tools/issues/1

I believe we are out of luck fellow rx2.  @NemisisDragon  as i did a search as well.

**Comment by cottinghamd** [comment]
Hi NemisisDragon,

This does not work with the XDJ-RX2 because the network connector in the player doesn't actually support the Pioneer ProDJ Link protocol. The network card in this player only allows for connection to Rekordbox in Export mode, but does not send information over the network such as track name / load status etc required for this software to function. This is also why you can't plug the XDJ-RX2 into a network and connect to other CDJ's.

This is not an issue / bug, just not supported at this time.

**Comment by EvanPurkhiser** [comment]
Closing this out, since as @cottinghamd pointed out, the RX is unfortunately not supported :(
