### ISSUE TITLE
XDJ-RX crashes

### ISSUE THREAD

**Issue by Tygronn** [EvanPurkhiser/prolink-tools#47]
So I was hoping I would be able to use this with my XDJ-RX (the original not the RX2) and whenever Prolink Tools makes a connection it crashes my XDJ pretty hard.

It just completely freezes, nothing responds. The power button kills the lights but everything on the screen portion stays. I have to turn the toggle back to on and back off once the boot screen appears.

I'm not entirely sure what other details I could provide but i'll be as helpful as I can.

**Comment by KayPure** [comment]
Since the XDJ RX dont Support the Prolink DJ Protocol, it wont work with this Controller. 

https://forums.pioneerdj.com/hc/en-us/community/posts/203113059/comments/203679119

 
"The LINK on the RX is ONLY for linking to rekordbox on your computer or a router with WiFi to connect rekordbox mobile. It can not exchange LINK data with other CDJs or DJM"

**Comment by EvanPurkhiser** [comment]
Like @KayPure unfortunately the XDJ-RX isn't supported.
